name: Checkout and Create Branch

on:
  workflow_dispatch:

jobs:
  create-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Clone the repository
        run: |
          git clone https://${{ secrets.MY_PERSONAL_ACCESS_TOKEN }}@github.com/Shankyrwt/Ansible_playbook.git
          cd Ansible_playbook

      - name: Create new branch
        run: |
          cd Ansible_playbook
          git checkout -b workflow/github-workflow/certain/version1.1.1

      - name: Push new branch
        run: |
          cd Ansible_playbook
          git push https://${{ secrets.MY_PERSONAL_ACCESS_TOKEN }}@github.com/Shankyrwt/Ansible_playbook.git workflow/github-workflow/certain/version1.1.1
