name: Sprint Release Notes

on:
  workflow_dispatch:
    inputs:
      sprint_name:
        description: 'Sprint name (e.g., Sprint5)'
        required: true
      version:
        description: 'Version for the release branch (e.g., v1.2.0)'
        required: true

jobs:
  create-release-notes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install requests jira

      - name: Generate release notes
        env:
          JIRA_URL: ${{ secrets.JIRA_URL }}
          JIRA_EMAIL: ${{ secrets.JIRA_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
        run: |
          python generate_release_notes.py "${{ github.event.inputs.sprint_name }}"

      - name: Prepare unique tag name
        id: prepare_tag
        run: |
          # Remove spaces and special characters, convert to lowercase
          TAG_NAME=$(echo "${{ github.event.inputs.sprint_name }}" | tr '[:upper:]' '[:lower:]' | sed 's/[^a-zA-Z0-9]/-/g')
          TIMESTAMP=$(date +%Y%m%d%H%M%S)
          UNIQUE_TAG_NAME="${TAG_NAME}-${TIMESTAMP}"
          echo "TAG_NAME=v${UNIQUE_TAG_NAME}" >> $GITHUB_OUTPUT

      - name: Prepare branch name
        id: prepare_branch
        run: |
          BRANCH_NAME="release/${{ github.event.inputs.version }}"
          echo "BRANCH_NAME=${BRANCH_NAME}" >> $GITHUB_OUTPUT

      - name: Create and checkout new branch from main
        run: |
          git checkout -b ${{ steps.prepare_branch.outputs.BRANCH_NAME }}

      - name: Pull latest changes from remote branch
        run: |
          git fetch origin
          git pull origin ${{ steps.prepare_branch.outputs.BRANCH_NAME }} --rebase || true

      - name: Configure Git author
        run: |
          git config --local user.email "${{ github.actor }}@users.noreply.github.com"
          git config --local user.name "${{ github.actor }}"

      - name: Commit changes
        run: |
          git add release_notes.md
          git commit -m "Add release notes for ${{ github.event.inputs.sprint_name }} - ${{ github.event.inputs.version }}" || echo "No changes to commit"

      - name: Push new branch
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
        run: |
          git push origin ${{ steps.prepare_branch.outputs.BRANCH_NAME }} --force-with-lease

      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.prepare_tag.outputs.TAG_NAME }}
          release_name: Release ${{ github.event.inputs.sprint_name }}
          body_path: release_notes.md
          draft: false
          prerelease: false
