name: Sprint Release Notes

on:
  workflow_dispatch:
    inputs:
      sprint_name:
        description: 'Sprint name (e.g., Sprint5)'
        required: true
      version:
        description: 'Release version (e.g., v1.2.0)'
        required: true

jobs:
  create-release-notes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install requests jira

      - name: Generate release notes
        env:
          JIRA_URL: ${{ secrets.JIRA_URL }}
          JIRA_EMAIL: ${{ secrets.JIRA_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
        run: |
          python generate_release_notes.py "${{ github.event.inputs.sprint_name }}"

      - name: Checkout main branch
        run: |
          git checkout main
          git pull origin main

      - name: Prepare branch name
        id: prepare_branch
        run: |
          BRANCH_NAME="release/${{ github.event.inputs.version }}"
          echo "BRANCH_NAME=${BRANCH_NAME}" >> $GITHUB_OUTPUT

      - name: Create and checkout new branch from main
        run: |
          git checkout -b ${{ steps.prepare_branch.outputs.BRANCH_NAME }}

      - name: Configure Git author
        run: |
          git config --local user.email "your-email@example.com"
          git config --local user.name "Your Name"

      - name: Commit changes
        run: |
          git add release_notes_*.md
          git commit -m "Add release notes for ${{ github.event.inputs.sprint_name }} - ${{ github.event.inputs.version }}"

      - name: Push new branch
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
        run: |
          git push origin ${{ steps.prepare_branch.outputs.BRANCH_NAME }}

      - name: Verify Release Notes Content
        run: |
          cat release_notes_*.md

  create-releases:
    needs: create-release-notes
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install requests jira

      - name: Fetch repository names from Jira tickets
        id: fetch_repos
        env:
          JIRA_URL: ${{ secrets.JIRA_URL }}
          JIRA_EMAIL: ${{ secrets.JIRA_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
        run: |
          python -c "import os; from jira import JIRA; jira = JIRA(server=os.environ['JIRA_URL'], basic_auth=(os.environ['JIRA_EMAIL'], os.environ['JIRA_API_TOKEN'])); sprint_name = '${{ github.event.inputs.sprint_name }}'; issues = jira.search_issues(f'sprint = \\"{sprint_name}\\" AND project = \\"SCRUM\\" AND status = Done', maxResults=1000); repos = set(); [repos.add(branch['repository']['name']) for issue in issues for branch in issue.fields.branches]; print(':'.join(repos))" > repos.txt

      - name: Create GitHub Releases in Different Repositories
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
        run: |
          repos=$(cat repos.txt)
          IFS=':' read -r -a repo_array <<< "$repos"
          for repo_name in "${repo_array[@]}"; do
            if [ -f "release_notes_$repo_name.md" ]; then
              gh release create ${{ github.event.inputs.version }} --repo $repo_name --title "Release ${{ github.event.inputs.version }} for ${{ github.event.inputs.sprint_name }}" --notes-file release_notes_$repo_name.md
            fi
          done
